
SDO_Exception::getCause

(^)

SDO_Exception::getCause — Get the cause of the exception.

说明

mixed SDO_Exception::getCause ( void )
Warning

此函数是实验性的。此函数的表象，包括名称及其相关文档都可能在未来的 PHP 发布版本
中未通知就被修改。使用本函数风险自担。

Returns the cause of this exception or NULL if the cause is nonexistent or
unknown. Typically the cause will be an SDO_CPPException object, which may be
used to obtain additional diagnostic information.

参数

None.

返回值

Returns the cause of this exception or NULL if the cause is nonexistent or
unknown.

