
Yaf_Dispatcher::throwException

(Yaf >=1.0.0)

Yaf_Dispatcher::throwException — 开启/关闭异常抛出

说明

public Yaf_Dispatcher Yaf_Dispatcher::throwException ([ bool $flag ] )

当意外的错误发生的时候，开启/关闭异常抛出。当开启的时候，Yaf将会抛出异常而不是
触发可捕捉的错误。

你也可以使用 application.dispatcher.throwException来达到相同的目的。

参数

flag

    bool

返回值

范例

Example #1 Yaf_Dispatcher::throwexception()example

<?php

$config = array(
    'application' => array(
        'directory' => dirname(__FILE__),
    ),
);
$app = new Yaf_Application($config);

$app->getDispatcher()->throwException(true);

try {
    $app->run();
} catch (Yaf_Exception $e) {
    var_dump($e->getMessage());
}
?>

以上例程的输出类似于：

string(59) "Could not find controller script /tmp/controllers/Index.php"

Example #2 Yaf_Dispatcher::throwexception()example

<?php

$config = array(
    'application' => array(
        'directory' => dirname(__FILE__),
    ),
);
$app = new Yaf_Application($config);

$app->getDispatcher()->throwException(false);

$app->run();
?>

以上例程的输出类似于：

PHP Catchable fatal error:  Yaf_Application::run(): Could not find controller script /tmp/controllers/Index.php in /tmp/1.php on line 12

参见

  • Yaf_Dispatcher::catchException() - 开启/关闭自动异常捕获功能
  • Yaf_Exception

